# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  installingDependencies:
    docker:
      - image: cimg/base:2022.11
        
    steps:
      - checkout
      - run: echo mynameis$MYNAME
      - run:
          name: Kick off new pipeline
          command: |
            curl --location --request POST 'https://circleci.com/api/v2/project/gh/vysnu96/ACR-Pipeline/pipeline' \
            --header 'Content-Type: application/json' \
            -u "${API_TOKEN}:"
           

    
workflows:
  version: 2
  workflowOne:
    jobs:
      - installingDependencies:
          context: uat
      
